### PR TITLE
Capture and use more info about channels/users

### PR DESCRIPTION
**Pull request by denetii**
Hi! I've been working on storing more data from discord channels/users, including:

- User tag/discriminator
- User avatar/icon
- Channel description
- Channel NSFW
- Channel's position in list

I've added some of these elements to the viewer, including user avatars/icons which can be toggled in the viewer settings. I kept the UI updates conservative, so some are unused or just appear in titles.

### CODE REVIEW

**Comment by chylex** [comment]
Thanks, looks good; whenever I have time I'll just cleanup a few things and add whatever's missing to the UI.

**Comment by chylex** [comment]
Since you didn't create a new branch and have it on `master` instead, is it ok for me to push some changes there directly or would you like to move the changes to a new branch first?

**Comment by denetii** [comment]
Hey, it's fine - you can push them on master.

**Comment by chylex** [comment]
Just as a heads up, I derped the merge commit quite a bit when I was rebasing so when I update your master there'll be a bunch of small errors :P it'll be fine after I squash the PR, but since you have it on master you should `git reset --hard origin/master` after I merge the PR.

**Pull request merged**
