### PR TITLE
Fix DHT button to show in Firefox with ViolentMonkey

### LINKED ISSUE #71: I don't have a DHT button
I'm using Windows 8.1 64 bit on Firefox with Violentmonkey. I have no DHT button in the desktop app or the website, but the tracker script shows up in the add on menu and it's toggled on. Help? 
bdce08f0a2aca703b6199641e2a876cc

### PR DESCRIPTION
**Pull request by robertpateii**
Fixes #71 by letting ViolentMonkey change the script context if needed, as in the case with Discord. Details on the issue.

### CODE REVIEW

**Comment by robertpateii** [comment]
@chylex Hello, thanks for the great logger. Hope this helps others running DHT in Firefox.

**Comment by robertpateii** [comment]
Bad news: if you fix this then it still doesn't work because you it can't find the channels. I think it's related to #69 and discord having changed their CSS class names. I assume this breaks it in every browser.

I tracked the problem down to this code, but I don't have time to dig into the problem in getReactProps. No doubt it's the changing UI that Chylex mentioned on issue 69.

`          
var props = DISCORD.getReactProps(channel);
          if (!props){
            return null;
          }
`

**Comment by chylex** [comment]
Considering https://github.com/chylex/Discord-History-Tracker/issues/71#issuecomment-515685618, I don't think this is going to work, unfortunately.

I might need to try various browsers and userscript managers, but from what I remember, this should only be an issue for Firefox+ViolentMonkey combination (and also Safari+TamperMonkey, but that case is not fixable for TM because of how limitations in Safari's extension system).

For Firefox, VM should be able to modify CSP headers to allow the userscript to run with full access when the website attempts to block it, but at the moment VM is not doing that.

**Comment by robertpateii** [comment]
Agreed. Discussion continued on #71.

**Pull request closed without merging**
