### PR TITLE
Added GUI togglable feature to include user tags and display names in logs.

### PR DESCRIPTION
**Pull request by excinera**
Salutations!
I saw Issue #36 and noticed that the modification was very similar to a feature I'd been planning to add to a fork of this project. 

This is the first pull request I've ever made, so I apologize if I'm doing it improperly. I did my best to preserve the original structure of the code.
dht-addition12

### CODE REVIEW

**Comment by chylex** [comment]
Thanks for the PR, I'll make some time to look at this and other open issues in a few weeks to get an update ready.

For the feature itself, I just have a few inputs and discussion points - once I have time I can implement these myself so you don't have to do anything, but I'd appreciate some thoughts:

- Adding an option in the viewer to display discriminators after usernames should be pretty easy, but I don't know how to deal with nicknames
- More on nicknames, since they can differ on each server, while not too important because it probably wouldn't be common, I'd rather make the nicknames into an array with all discovered nicknames for that user; again, idk how to display that in the viewer
- The options UI height needs to be increased

**Comment by excinera** [comment]
That's actually something I've been planning on addressing -- at least in my own fork, which would collect more complete metadata. The idea of having an array for user nicknames per server is very good, I think.

I was also planning on having an array for stuff like custom server emotes as well (obviously, scraping message reactions at all would be a toggleable option as well).

I may end up being too busy to finish that part of it, but I think restructuring savefiles for display-name arrays would be very doable (and, of course, necessary prior to adding a viewer feature for them, lest a bunch of people scrape logs with one-nickname-per-user structure and require the viewer to implement backwards-compatibility for files created by both versions).

**Comment by chylex** [comment]
Just a note; the viewer is intended to be backwards compatible with all previous archive formats. Generally, adding new properties to the format is fine but should be as compact as possible, modifying existing properties will only happen if there's a good reason and the viewer can easily identify which format is used.

For display names, since those are separate and don't affect the "canon" `username#tag` identifier of the account, it should be a new optional property that's only present if at least one server-specific nickname is scraped (not sure how useful it'd be to know which server each nickname is from, I think for simplicity, the viewer could have a panel with usernames with all scraped nicknames listed, in lieu of the `AKA` note in DM headers).

**Comment by chylex** [comment]
I'll release an update to get DHT working again after the Discord update, and get back to this PR later once I have more time to get the discussed changes & viewer done.

**Comment by chylex** [comment]
Since a similar PR was opened, I'll try to deal with this first so that both of you get credit in the contributor list. The other PR includes user discriminators but not display names, and I don't want to merge display names that aren't per-server as we discussed, so how about this:

- I will revert display names in your PR branch and only store discriminators (although it says your PR is from `master`, so let me know first if it's ok for me to do that since I don't want to mess up your `master` branch)
- I'll merge the discriminators so that you get contributor credit
- If you still want to add per-server nicknames, you can open a new PR

**Comment by excinera** [comment]
Hi! This sounds great. I had mostly forgotten about that pull request 
(although it was one of those things I'd think about once every four 
months or so, when the sun was coming up and tracing a line over the 
mountains). I have been using DHT a lot recently, though, so it will 
definitely be a help to me.

All that stuff you said sounds fine to me.

**Pull request merged**
